MyWallet/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyWallet.Extensions;
using MyWallet.Models;
using MyWallet.Services.Interfaces;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyWallet.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.GetCurrentUserId();
            var categories = await _categoryService.GetAll(userId);
            return View(categories);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var userId = User.GetCurrentUserId();
            var categories = await _categoryService.GetAll(userId);
            return View(new CreateCategory
            {
                Categories = new SelectList(categories, "Id", "Name")
            });
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(CreateCategory model)
        {
            if (!ModelState.IsValid) return RedirectToAction(nameof(Create));

            var userId = User.GetCurrentUserId();
            if (!model.Id.HasValue)
                await _categoryService.Add(userId, model.Name, model.Color, model.ParrentId);
            else
                await _categoryService.Update(userId, model.Id.Value, model.Name, model.Color, model.ParrentId);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var userId = User.GetCurrentUserId();
            var categories = await _categoryService.GetAll(userId);
            var editCategory = categories.SingleOrDefault(x => x.Id == id);

            return View(nameof(Create), new CreateCategory
            {
                Id = editCategory.Id,
                Color = editCategory.Color,
                Name = editCategory.Name,
                Categories = new SelectList(categories, "Id", "Name", editCategory.Parrent?.Id)
            });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var userId = User.GetCurrentUserId();
            await _categoryService.Remove(userId, id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MyWallet/Controllers/HistoryLinesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyWallet.Data.ValueObjects;
using MyWallet.Extensions;
using MyWallet.Models;
using MyWallet.Services.Interfaces;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyWallet.Controllers
{
    [Authorize]
    public class HistoryLinesController : Controller
    {
        private readonly IHistoryLinesService _historyLinesService;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public HistoryLinesController(IHistoryLinesService historyLinesService, ICategoryService categoryService, IMapper mapper)
        {
            _historyLinesService = historyLinesService;
            _categoryService = categoryService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var from = DateTime.Now.Date.AddDays(-DateTime.Now.Day + 1);
            var to = DateTime.Now.Date;
            var userId = User.GetCurrentUserId();
            var lines = await _historyLinesService.GetAll(userId, DateRange.Empty);

            var categories = (await _categoryService.GetAll(userId))
                .Where(x => x.Parrent == null && x.Child.Any())
                .ToArray();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");

            return View(new HistoryLinesModel
            {
                From = from,
                To = to,
                Lines = _mapper.Map<HistoryLineModel[]>(lines)
            });
        }

        [HttpPost]
        public async Task<IActionResult> Index(
            DateTime? from,
            DateTime? to,
            Guid? categoryId)
        {
            var userId = User.GetCurrentUserId();
            var lines = await _historyLinesService.GetAll(userId, new DateRange(from.Value, to.Value), categoryId);

            return PartialView("_HistoryLines", _mapper.Map<HistoryLineModel[]>(lines));
        }

        [HttpGet]
        public async Task<IActionResult> Create([FromServices] ICategoryService categoryService)
        {
            var userId = User.GetCurrentUserId();
            var categories = await categoryService.GetAll(userId);
            return View(new CreateHistoryLine
            {
                Categories = new SelectList(categories, "Id", "Name")
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateHistoryLine model)
        {
            if (!ModelState.IsValid) return View(model);

            await _historyLinesService.AddCredit(model.Name, model.Amount, model.CategoryId);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _historyLinesService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MyWallet/Controllers/StatisticController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyWallet.Data.ValueObjects;
using MyWallet.Extensions;
using MyWallet.Models;
using MyWallet.Services.Interfaces;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyWallet.Controllers
{
    [Authorize]
    public class StatisticController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IStatisticService _statisticService;
        private readonly IMapper _mapper;

        public StatisticController(ICategoryService categoryService, IStatisticService statisticService, IMapper mapper)
        {
            _categoryService = categoryService;
            _statisticService = statisticService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.GetCurrentUserId();
            var range = RangeTypes.Day;
            var (currentRange, prevRange) = GetRanges(range);

            var statisticItems = await _statisticService.GetStatistic(userId, prevRange, currentRange);
            var categories = (await _categoryService.GetAll(userId))
                .Where(x => x.Parrent == null && x.Child.Any())
                .ToArray();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");

            return View(_mapper.Map<StatisticItemModel[]>(statisticItems));
        }

        [HttpPost]
        public async Task<IActionResult> Index(
            RangeTypes rangeType,
            Guid? categoryId)
        {
            var (currentRange, prevRange) = GetRanges(rangeType);
            var userId = User.GetCurrentUserId();
            var statisticItems = await _statisticService.GetStatistic(userId, prevRange, currentRange, categoryId);

            return PartialView("_Statistic", _mapper.Map<StatisticItemModel[]>(statisticItems));
        }

        private static (DateRange thisRange, DateRange prevRange) GetRanges(RangeTypes range)
        {
            return range switch
            {
                RangeTypes.Day => (DateRange.Day, DateRange.PrevDay),
                RangeTypes.Week => (DateRange.Week, DateRange.PrevWeek),
                RangeTypes.Month => (DateRange.Month, DateRange.PrevMonth),
                _ => throw new NotImplementedException()
            };
        }
    }
}

MyWallet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyWallet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyWallet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Месяц</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HistoryLines" asp-action="Index">Транзакции</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistic" asp-action="Index">Статистика</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <ul class="navbar-nav flex-grow-1">
                            @if (!SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" href="#">@User.Identity.Name</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a>
                                </li>
                            }
                        </ul>

                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                @await RenderSectionAsync("LeftBar", required:false)
            </div>
            <div class="col-6">
                @RenderBody()
            </div>
            <div class="col-3" style="padding-top:25px">
                @await RenderSectionAsync("RightBar", required:false)
            </div>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyWallet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/js/Chart.js/chart.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>